### ISSUE TITLE
Clarify Hosted Platform shutdown

### ISSUE THREAD

**Issue by juzam** [owntracks/booklet#14]
In a recent thread in the Node-Red Google Group a user had a problem connecting to the Hosted plaftorm, another user pointed out that the booklet still refers to the platform and this is confusing.

The links are:
[http://owntracks.org/booklet/tech/proghosted/](http://owntracks.org/booklet/tech/proghosted/)
[http://owntracks.org/booklet/features/hosted/](http://owntracks.org/booklet/features/hosted/)

a warning at the top of those pages pointing to [community post](https://community.owntracks.org/topic/117/hosted-sunset-hosted-is-shutting-down/) should suffice I think.

Unfortunately I'm not able to submit a pull request myself at the moment.

**Comment by jpmens** [comment]
I'm confused b/c we explicitly removed that. Searching through the Booklet's source, I see only two case-insensitive `hosted`s:

![jmbp-2629](https://cloud.githubusercontent.com/assets/60706/14428139/13ace71e-fff8-11e5-9646-f26455c6173b.png)

There may well be other copies of the Booklet floating around of course, but ours doesn't mention the platform any longer.

**Comment by jpmens** [comment]
Removed mention in `privacy`; thanks for that heads-up. ;-)

**Comment by jpmens** [comment]
Now I actually click on your links and find the pages ... Travis build error, I suppose: removed pages aren't actually removed. Addressing now. Thanks @juzam

**Comment by jpmens** [comment]
Pages deleted

**Comment by juzam** [comment]
Thank you @jpmens. I'll update the Nod-Red thread with this issue.
