### ISSUE TITLE
Pages that need a rewrite 

### ISSUE THREAD

**Issue by binarybucks** [owntracks/booklet#19]
- [ ] http://owntracks.org/booklet/features/tls/#android (Screenshots)
- [ ] http://owntracks.org/booklet/features/tls/#ios (Screenshots)
- [ ] http://owntracks.org/booklet/features/tls/#manual-configuration-on-android (Screenshots, functionality changed)
- [ ] http://owntracks.org/booklet/features/tls/#obtain-a-certificate-and-key (s/startssl/letsencrypt/g?)
- [x] http://owntracks.org/booklet/features/tlscert/#android (import file into the app)
- [x] http://owntracks.org/booklet/features/friends/#who-is-that (no contact book feature on Android)
- [x] http://owntracks.org/booklet/features/waypoints/ (describe setup on Android)
- [x] http://owntracks.org/booklet/features/waypoints/#setting-up-ibeacons (describe setup on Android)
- [x] http://owntracks.org/booklet/features/waypoints/#remote-loading-of-waypoints (describe setWaypoints cmd)
- [x] http://owntracks.org/booklet/features/comparison/ (HTTP mode on Android, s/TLS with cert in filesystem    /Custom TLS CA cert/g, Remote configuration on Android)
- [x] http://owntracks.org/booklet/features/comparison/#android (drop user-provided certificates via an absolute path, drop button to share a Google Maps link that places a marker at lastKnownLocation
  , drop Google Fused Location Provider...)
- [x] http://owntracks.org/booklet/features/android/#setup (no Advanced Connection Preferences, specify the absolute filesystem path)
- [ ] http://owntracks.org/booklet/features/encrypt/ (explain optional encrypted array payload)
- [x] http://owntracks.org/booklet/features/remoteconfig/ (document setConfiguration)
- [x] http://owntracks.org/booklet/features/setwaypoints/ (also on Android now)
- [x] http://owntracks.org/booklet/tech/json/#notes (no extra heading for that, move do description of `locked` attribute) 
- [x] http://owntracks.org/booklet/tech/http/ (move to Features?)
- [x] http://owntracks.org/booklet/ideas/ (drop links to binarybucks/mqttitude. Repo will be removed shortly) 
- [x] http://owntracks.org/booklet/faq/ (rework with annoying questions) 
- [ ] http://owntracks.org/booklet/guide/clients/#o2s (drop?)
- [ ] Consider merging http://owntracks.org/booklet/features/comparison/, http://owntracks.org/booklet/features/android/, http://owntracks.org/booklet/features/ios/ to http://owntracks.org/booklet/guide/apps/

**Comment by jpmens** [comment]
So many changes have occurred over time, I'm now closing this.
