### ISSUE TITLE
traccar documentation wrong

### ISSUE THREAD

**Issue by deisi** [owntracks/booklet#38]
https://owntracks.org/booklet/features/traccar/
Is not understandable or wrong.

I just stetted up traccar on android and observed the following:

- Identifier in traccar is *not* made up like the mqtt topic, instead it is *only the tracker id*. So in my case 
  it was just `md`. Device ID is completely ignored.
  Just to be clear, the doc suggested the identifier would be: `owntracks/username/device-id`. Instead it was `tracker-id`, so literally the only thing the documentation said not to be in the identifier. 
- You have to add the device to traccar *before* connecting owntrack client. Otherwise you will get a http 400 error.

Also I don't understand why there is so much text on the http payload and stuff. People will look for information how to set up a connection between traccar server and owntracks. Development related stuff should be in another section, or at least subsection.

I would volunteer to improve the documentation, but I also wonder if the thing with the identifier is not a bug in android. Having only two letter identifiers limits you and might even be a security issue, because the identifiers are also some kind of secret.

**Comment by jpmens** [comment]
Could it be that you are mistaking the screenshot in that page of the Booklet with something you thinkm is in Android? 

The identifier in traccar is anything you want; in Traccar terms it is a _uniqueId_. In recent versions of our Android app it should be the topic (just as in the very recent, as yet unreleased, version of our iOS app). 

The 400 status is a Traccar thing. Do not blame us for that, please! Traccar expects you set up the device before said device starts publishing.

Apart from all that, we are always game for people who want to improve on our documentation.

**Comment by deisi** [comment]
> Could it be that you are mistaking the screenshot in that page of the Booklet with something you thinkm is in Android?

I don't think so. I know that it is a screenshot from the traccar web-interface.

> The identifier in traccar is anything you want;

yes, but it gets setted via the owntracks app itself, and as far as I can tell, the app uses the `tracker-id` from the owntracks app. Is there any way of changing it?

> In recent versions of our Android app it should be the topic

I use version 2.1.2 and it is not the topic as of right now. So this is a bug?

> The 400 status is a Traccar thing. Do not blame us for that, please! 

Sry, I didn't want to blame anybody here, I just wanted to point out that the order in witch you set up your system matters and it would be helpful if the documentation tells you so.

**Comment by deisi** [comment]
>HTTP POST payloads shall contain at least the elements `lat`, `lon`, `_type:location`, `tst`, and either or both of `tid` and `topic`. If `topic` is given in the payload, that will be used as Traccar's `uniqueId` (in which case `tid` will be added to attributes), else `tid`.

I think now I understand what this wants to tell me... 

Okay, now I would say, it is not wrong, but its really really hard to understand if you are not an owtracks dev. At least its written from the perspective of an owntracks dev in my opinion.

I would suggest to change the documentation more into an: If you want to use owntracks with traccar, then do this ....

At the end a section that deals with the quirks and nifty things like setting up a different topic.

**Comment by deisi** [comment]
fb62a9d  as a first proposed fix.

**Comment by jpmens** [comment]
closed via #39
