### ISSUE TITLE
Missing Friend Bookmark Feature

### ISSUE THREAD

**Issue by jgoerzen** [owntracks/booklet#58]
Over at https://owntracks.org/booklet/features/friends/, there is supposed to be a way to "bookmark" a friend to associate it with an address book contact.  I'm not seeing that icon at all.

* **App build number**: 2.1.3
* **Android version**: 10
* **Device**: Pixel 2 XL

**Comment by jpmens** [comment]
How is `friend as contained in the iOS address book` to be misunderstood?

Anyway, will add `iOS only` to the description.
