### ISSUE TITLE
Mosquitto version used in docs outdated

### ISSUE THREAD

**Issue by stevenroose** [owntracks/booklet#69]
I'm installing on latest Ubuntu LTS and there seem to be quite some breaking changes to the API of Mosquitto. The version Ubuntu has is `2.0.11`.

Some changes I noticed are

- `port` field in config is deprecated
- `-v` flag of `mosquitto_pub` doesn't exist anymore (used here https://owntracks.org/booklet/guide/broker/)

**Comment by jpmens** [comment]
Thank you. I have changed port into listener, but can't find where you see we use -v on mosquitto_pub (I see _sub only.)

**Comment by jpmens** [comment]
Thank you. We're revamping the Booklet at this moment and are setting preference on what we call Quicksetup.
