### ISSUE TITLE
Link to openHAB integration outdated

### ISSUE THREAD

**Issue by amotl** [owntracks/booklet#71]
Dear JP and Christoph,

while exploring the documentation a bit more, I discovered that the section about the openHAB integration [^1] points to a repository which has been archived. It still talks about the »Mqttitude Binding« [^2], which I think is a thing of the past. Do you know of any updated resources on this matter, where the link could be adjusted to?

With kind regards,
Andreas.

[^1]: https://owntracks.org/booklet/guide/clients/#openhab
[^2]: https://github.com/openhab/openhab1-addons/wiki/Mqttitude-Binding

**Comment by jpmens** [comment]
I believe [this is the current documentation](https://v2.openhab.org/addons/bindings/mqttitude1/) of the binding.
