### ISSUE TITLE
Update pkcs12 steps for newer openssl binary

### ISSUE THREAD

**Issue by syphrv** [owntracks/booklet#75]
Hello! Reporting an issue with: https://owntracks.org/booklet/features/tlscert/#pkcs12

Please add -legacy to this command. I kept having iOS .otrp "incorrect file or passphrase" errors getting a client certificate working and it's because the openssl v3 binary I was using generates them differently. Once I added -legacy, it solved the error :)

```
openssl pkcs12 -legacy \
  -export \
  -in jjolie.crt \
  -inkey jjolie.key \
  -name "Jane's certificate/key" \
  -out jjolie.p12
```

**Comment by jpmens** [comment]
Thanks for raising this. Fixed.
