### ISSUE TITLE
Some JSON settings not explained in the booklet

### ISSUE THREAD

**Issue by speckenbuettel** [owntracks/booklet#85]
Hi,

I noticed that some JSON settings are not explained under https://owntracks.org/booklet/tech/json, which are visible in the advanced settings on an Android device.

The missing JSON selectors are:

- connectionTimeoutSeconds
- debugLog
- pegLocator

Would be interesting to know what is behind these ...

Thanks and best regards,
Falk

**Comment by jpmens** [comment]
Thank you for reporting that.

**Comment by growse** [comment]
- `connectionTimeoutSeconds`: int (default 30) - TCP timeout for establishing a connection to the MQTT / HTTP broker
- `debugLog`: bool (default false) - whether or not debug logs should be shown in the log viewer / exporter activity
- `pegLocatorFastestIntervalToInterval`: bool (default false) - if true, requests that that the device provide locations no faster than the specified interval. Location providers often use the requested interval as a "at least every" setting, and may return locations more frequencly. Some people wanted the behaviour where it also meant "no more frequently than", so this setting lets them specify this

**Comment by speckenbuettel** [comment]
Thanks a lot!
