### ISSUE TITLE
_type=status documentation is missing

### ISSUE THREAD

**Issue by gene1wood** [owntracks/booklet#89]
I see in the `rec` JSON files records like this

```
2024-11-28T01:10:12Z    status                  {"_type":"status","_id":"267c4b0d","android":{"hib":1,"bo":0,"loc":0,"ps":0,"wifi":1}}
```

But looking in this page https://owntracks.org/booklet/tech/json/

I don't see any mention of `_type=status`

Could details about these records be added to the JSON documentation page?

**Comment by ckrey** [comment]
example payload for iOS in the owntracks/iOS#778
I will update the booklet for iOS

**Comment by ckrey** [comment]
done for iOS with 2def6e55704e517a0602e1e67bcbdeee079a604d

**Comment by jpmens** [comment]
I have added Android descriptions taken from top of https://github.com/owntracks/android/issues/1618

Thank you, @gene1wood, for reporting. Closing as fixed.
