### ISSUE TITLE
Yet another recorder "replacement"

### ISSUE THREAD

**Issue by sparky** [owntracks/booklet#90]
Short story long...

I like to have all data viewable and accessible in the same place. Since many tools I use already used Prometheus + Grafana for monitoring, and Grafana now has a nice Geo panel, I have decided to dump the device location into the same stack.

https://github.com/sparky/owntracks-prometheus-relay/

This is a very simple recorder replacement that just receives the data from the app over HTTP (only Android tested). Then exposes an endpoint for Prometheus to scrape the information.

Once I was mostly done I realised that there is a major (for me) issue in Prometheus. It allows to record data with a user-specified timestamp. However, that timestamp must be within last 1 hour. Any older data will be ignored. This makes it not very suitable for recording location information from places with poor or no internet connection.

I am not sure whether there is a fix/workaround for that. If I do not find one, I might try to dump the data to ProstgreSQL instead.

Best Regards,
-- Iskra

P.S. https://owntracks.org/booklet/guide/clients/ mentions [Prometheus OwnTracks Exporter](https://github.com/linusg/prometheus-owntracks-exporter) -- at first I thought it would be exactly what I later set to write. However, that one is only a "OwnTracks Recorded Exporter", that is, it exposes the health of the Recorder service to Prometheus, not the actual location data.

**Comment by jpmens** [comment]
Thanks, but the repo says:

> For this reason, I am abandoning this solution, at least until I figure out how to make Prometheus accept older data.

So I am closing this.
